### PR TITLE
Parallelize isotropize

### PR DESCRIPTION
**Pull request by roxyboy**
I implemented @shoyer 's amazing `numpy_groupies` hack to parallelize the isotropization of spectra. This addresses issues #9 and #87 .

### CODE REVIEW

**Comment by rabernat** [comment]
This is cool Takaya! We could also potentially use this in xhistogram

I will review this after the Thanksgiving holiday.

p.s. @shoyer is not the creator of numpy_groupies.

**Comment by rabernat** [comment]
p.s. Isn't this going into xarray itself? Is it necessary to put it in xrft?

**Comment by roxyboy** [comment]
> p.s. Isn't this going into xarray itself? Is it necessary to put it in xrft?

I think it eventually is going to but I checked the `xarray` issue log and it seems that there's still some issues for it to be implemented upstream. So I figured I'd just add it to `xrft` in the mean time.

**Comment by roxyboy** [comment]
@rabernat Do you think we should keep this PR out until `numpy_groupies` gets implemented more upstream?

**Review by rabernat — APPROVED** [review]
This looks great! Do we have tests for this feature already? If so, I approve.

**Comment by roxyboy** [comment]
> This looks great! Do we have tests for this feature already? If so, I approve.

The `test_isotropize` tests isotropization for both chunked and non-chunked data so I think the tests cover this feature.

**Pull request merged**
