### PR TITLE
Readthedocs.io

### PR DESCRIPTION
**Pull request by roxyboy**
I'm not quite sure of the procedure but do you have to link the xrft Github repo to Read the Docs...?

### CODE REVIEW

**Comment by rabernat** [comment]
I recommend you read the read the docs docs! 😝 
https://docs.readthedocs.io/en/latest/#user-docs

Yes, we will have to enable rtd for this repo. Probably the best way to do that is to first transfer it off my personal account and into the xgcm organization.

Do you think that is a good idea?

**Comment by roxyboy** [comment]
Ok, so should I send you the files relevant for the Readthedocs via email so you can transfer it?

**Comment by rabernat** [comment]
no no no. I want to give you the permissions to do everything yourself! I need to get out of the loop! :)

**Comment by rabernat** [comment]
Have you built the sphinx docs locally?

**Comment by roxyboy** [comment]
Oh, ok... Not sure of what details would change but sure, you can add it to xgcm. I saw the sphinx file already existed in the xrft repo so no, I didn't build sphinx locally.

**Comment by rabernat** [comment]
Ok, so your first step needs to be to build the docs locally using sphinx to ensure that the docs you wrote actually compile and look right.
http://www.sphinx-doc.org/en/master/

**Comment by roxyboy** [comment]
Ok, will work on it.

**Comment by roxyboy** [comment]
Do I build the sphinx docs in my local xrft repo?

**Comment by roxyboy** [comment]
Ok, I seem to have it working locally on my Mac. The html files were generated correctly. What should I do now to integrate xrft with xgcm and add the docs...?

**Comment by rabernat** [comment]
I have moved the repo to the xgcm org:
https://github.com/xgcm/xrft

I created a "team", added you to it, and gave it ownership to xgcm/xrft:
https://github.com/orgs/xgcm/teams/xrft-dev

You now have complete control over xrft (same as me). You may add new
collaborators, integrate with existing services, whatever you want!

**Comment by roxyboy** [comment]
So... now I fork the xgcm/xrft, add the Readthedoc files to my new fork, push it, create a pull request and then merge it in xgcm/xrft?

**Comment by rabernat** [comment]
Your pull request has automatically transferred here (see #30). You don't have to re-fork--github will redirect the old link to `rabernat/xrft` to `xgcm/xrft`.

You can merge your own PR. As for how to integrate with RTD, you should look at their docs for that:
https://docs.readthedocs.io/en/latest/getting_started.html

**Pull request merged**
