### PR TITLE
Refactor duplicated code in xrft.py into separate functions; add one test; format with black

### PR DESCRIPTION
**Pull request by simonkeys**
I'm thinking of adding some features to xrft, so I started out by doing some refactoring. I added one test to check the case of ifft with unsorted coordinates.

If this is too many changes at once, I can break it up into more PRs with fewer commits.

### CODE REVIEW

**Comment by roxyboy** [comment]
Thanks a lot for this refactoring @simonkeys ! Just out of curiosity, what features are you planning to add?

**Comment by simonkeys** [comment]
Basically whatever comes up in the project I'm using it for (image processing for interferometric microscopy). So far I'm thinking
- interoperability with pint-xarray
- function returning the coordinates that would appear in a fft
- possible option to back with scipy fft library instead of numpy (maybe a speed-up? I'm not sure about that)
- option to do a fft with a real dimension but then return negative and positive frequencies instead of just positive

**Comment by roxyboy** [comment]
> * interoperability with pint-xarray
> * function returning the coordinates that would appear in a fft
> * possible option to back with scipy fft library instead of numpy (maybe a speed-up? I'm not sure about that)
> * option to do a fft with a real dimension but then return negative and positive frequencies instead of just positive

All features you suggest would be a great addition to `xrft`. Regarding scipy over numpy, this is something I've thought about during the early stages of developing `xrft` but do you see any clear advantages of one over the other?

**Comment by roxyboy** [comment]
All the checks passed so I'm going to merge this PR. I'd be happy to continue the discussion if you could raise an issue on Github :)

**Pull request merged**
