### PR TITLE
Refactoring for Python 3.12

### PR DESCRIPTION
**Pull request by roxyboy**
Refactoring due to deprecations in numpy and pandas.

### CODE REVIEW

**Comment by roxyboy** [comment]
@cgahr The tests all pass for Python versions 3.8-3.11 but doesn't due to a deprecation in `pkgutil`... We can drop the Github workflow for Python 3.12 for the time being? I'm open to suggestions.

**Comment by roxyboy** [comment]
@xgcm/xrft-dev @jbusecke Are others aware of fix to make the Github workflow work for Python 3.12? The deprecation in `pkgutils` breaks it.

**Comment by cgahr** [comment]
I think adding `- pip` just before `pip:` in thr environment.yml might force conda to install a newer pip version, solving the issue.

**Comment by cgahr** [comment]
Ahh nevermind, this shouldn't make a difference, my bad.

**Comment by roxyboy** [comment]
@cgahr Managed to sort out the workflow for Python 3.12 :) Can you give this version a try for your PRs?

**Comment by cgahr** [comment]
All tests succeed for me!

**Pull request merged**
