### PR TITLE
Simpler examples

### PR DESCRIPTION
**Pull request by roxyboy**

### CODE REVIEW

**Comment by roxyboy** [comment]
@rabernat Let me know if the mooring example is good?

**Comment by rabernat** [comment]
Thanks for getting this started. However, I was hoping we could use current meter data, which would should the inertial frequency, tidal frequencies, etc.

**Comment by rabernat** [comment]
Thanks for getting this started. However, I was hoping we could use current meter data, which would should the inertial frequency, tidal frequencies, etc.

**Comment by rabernat** [comment]
Thanks for getting this started. However, I was hoping we could use current meter data, which would should the inertial frequency, tidal frequencies, etc.

**Comment by rabernat** [comment]
Thanks for getting this started. However, I was hoping we could use current meter data, which would should the inertial frequency, tidal frequencies, etc.

**Comment by navidcy** [comment]
Perhaps the first example could be a synthetic single? E.g., construct a signal as a sum of two frequencies and use `xrft.dft` to compute the spectrum and compare with what you actually expect?

**Comment by rabernat** [comment]
Great suggestion @navidcy!

**Comment by navidcy** [comment]
@roxyboy, is there a way to see a preview of the docs after, e.g., this PR?

**Pull request closed without merging**
