### PR TITLE
Fix typos on test_padding.py

### PR DESCRIPTION
**Pull request by santisoler**
Fix a few typos on docstrings and comments of test functions in `test_padding.py`

### CODE REVIEW

**Comment by roxyboy** [comment]
Thanks for this PR in addition to #179 @santisoler ! Could you run `black` on your code to fix the formatting?
Also, should be drop support for Python 3.6...? @rabernat

**Comment by santisoler** [comment]
> Could you run black on your code to fix the formatting?

Sure! Black is complaining because the stable version has changed some styles, like simple operands of power that now should be hugged (e.g. `e**a` instead of `e ** a`). I'll open a new PR for making the changes on the entire `xrft`. If we merge it and then update this one, Black shouldn't complain here.

**Comment by santisoler** [comment]
@roxyboy I think this is ready to be merged now that we solved the issue with Black. Do you agree?

**Comment by roxyboy** [comment]
> @roxyboy I think this is ready to be merged now that we solved the issue with Black. Do you agree?

Yes, we can merge this :)

**Pull request merged**
