### PR TITLE
Consolidate CI env files

### PR DESCRIPTION
**Pull request by jbusecke**
This PR does two things:
- [x] Consolidate Ci environments into a single file, reducing the maintenance burden
- [x] Remove a few dependencies that are not necessary for the CI (black, setuptools)

### CODE REVIEW

**Comment by jbusecke** [comment]
Ignoring the linter failures, those will be fixed by #182. If @roxyboy and @santisoler are ok, I would merge this now.

**Comment by jbusecke** [comment]
Actually lets add 3.9 for good measure.

**Comment by jbusecke** [comment]
Ok cool that CI seems in good shape. Let me know if I should merge this.

**Comment by roxyboy** [comment]
> Ok cool that CI seems in good shape. Let me know if I should merge this.

All good on my end to merge ;) Thanks @jbusecke

**Pull request merged**
